export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const REGISTER = "REGISTER"
export const ADD_EXERCISE = "ADD_EXERCISE"
export const ADD_NUTRITION = "ADD_NUTRITION"
export const GET_LOGS = "GET_LOGS"