export const nutrition = [
    {
        type: "1,800 Calories",
        image: require('../assets/nutrition/image/1800.jpg'),
       data = [
            {
                name: "Day 1:",
               image: require('../assets/nutrition/image/1800.jpg'),
                procedure: [
                            "Breakfast (382 calories)",
                            "Avocado-Egg Toast",
                            "• 1 slice whole-grain bread",
                            "• 1/2 medium avocado",
                            "• 1 large egg, cooked in 1/4 tsp. olive oil or coat pan with a thin layer of cooking spray (1-second spray) Season egg with a pinch of salt and pepper.",
                            "• 2 clementines",
                            "Morning Snack(305 calories)",
                            "•	1 medium apple",
                            "•	2 Tbsp. peanut butter",
                            "Lunch (407 calories)",
                            "• 2 cups Ravioli & Vegetable Soup",
                            "• 2 diagonal slices baguette (1/4 inch thick), preferably whole-wheat",
                            "• 3 Tbsp. shredded Cheddar cheese Top baguette slices with 1 1/2 Tbsp. cheese each and a pinch of pepper. Toast until cheese is melted.",
                            "Afternoon Snack(169 calories)",
                            "•	4 Tbsp. hummus",
                            "•	1 cup sliced cucumber",
                            "•	2 medium carrots",
                            "Dinner (560 calories)",
                            "Salmon & Vegetables",
                            "• 4 oz. baked salmon",
                            "• 1 cup roasted Brussels sprouts",
                            "• 1 cup brown rice",
                            "• 1/8 tsp. salt",
                            "• 1/8 tsp. pepper",
                            "• 1 Tbsp. walnuts",
                            "Vinaigrette",
                            "• Combine 1 1/2 tsp. each olive oil, lemon juice and maple syrup; season with 1/8 tsp. salt.",
                            "Toss Brussels sprouts in 1/2 tsp. olive oil and bake at 425°F until lightly browned, 15 to 20 minutes. Coat salmon with 1/4 tsp. olive oil or a thin layer of cooking spray (1-second spray) and season with 1/8 tsp. each salt and pepper. Bake at 425°F until opaque in the middle, 4 to 6 minutes. Serve Brussels sprouts, salmon and brown rice drizzled with vinaigrette and topped with walnuts.",

                ]
            },
            {
                name: "Day 2:",
                image: require('../assets/nutrition/image/1800.jpg'),
                procedure: [
                            "Breakfast (382 calories)",
                            "Avocado-Egg Toast",
                            "• 1 slice whole-grain bread",
                            "• 1/2 medium avocado",
                            "• 1 large egg, cooked in 1/4 tsp. olive oil or coat pan with a thin layer of cooking spray (1-second spray) Season egg with a pinch of salt and pepper.",
                            "• 2 clementines",
                            "Morning Snack(172 calories)",
                            "•	8 dried apricots",
                            "•	8 walnut halves",
                            "Lunch (441 calories)",
                            "Leftover soup",
                            "• 2 cups Ravioli & Vegetable Soup",
                            "• 2 diagonal slices baguette (1/4 inch thick), preferably whole-wheat",
                            "• 3 Tbsp. shredded Cheddar cheese Top each baguette slice with 1 1/2 Tbsp. cheese and a pinch of pepper. Toast until cheese is melted.",
                            "• 1 clementine",
                            "Afternoon Snack(169 calories)",
                            "•	4 Tbsp. hummus",
                            "•	2 medium carrots",
                            "Dinner (533 calories)",
                            "•	1 1/2 cups Delicata Squash & Tofu Curry",
                            "•	Serve curry over 1 cup brown rice.",
                            "Evening Snack (133 calories)",
                            "• 2 Medjool dates",
                            "Meal Prep Tip: Make Maple-Nut Granola for tomorrow. You can also buy granola, to make things easier. Aim for a granola that has around 130 calories (or less) and less than 6 grams of sugar per 1/4 cup.",

                ]
            },
            {
                name: "Day 3:",
                image: require('../assets/nutrition/image/1800.jpg'),
                procedure: [
                            "Breakfast (405 calories)",
                            "•	1/2 cup Maple-Nut Granola",
                            "•	1 cup nonfat plain Greek yogurt",
                            "•	1/4 cup blueberries",
                            "Morning Snack(128 calories)",
                            "•	3 Tbsp. hummus",
                            "•	2 medium carrots",
                            "Lunch (443 calories)",
                            "Apple & Cheddar Pita Pocket",
                            "• 1 whole-wheat pita round (6-1/2-inch)",
                            "• 1 Tbsp. mustard",
                            "• 1/2 medium apple, sliced",
                            "• 1 1/2 oz. Cheddar cheese",
                            "• 1 cup mixed greens",
                            "Cut pita in half and spread mustard inside. Fill with apple slices and cheese. Toast until the cheese begins to melt. Add greens and serve.",
                            "• 1 clementine",
                            "Afternoon Snack (278 calories)",
                            "• 1/2 medium apple, sliced",
                            "• 1 Tbsp. peanut butter",
                            "• 1/4 cup Maple-Nut Granola",
                            "Dip apple slices into peanut butter and granola.",
                            "Dinner (507 calories)",
                            "• 1 Moroccan-Style Stuffed Pepper",
                            "• 2 cups spinach",
                            "Sauté spinach in 1 tsp. olive oil with a pinch of salt and pepper.",
                            "• 1 cup sliced carrots, steamed",
                            "Evening Snack (50 calories)",
                            "• 1 Tbsp. chocolate chips, preferably dark chocolate",
                            "Meal Prep Tip: Hard-boil 2 eggs-save one for Day 5. Make Carrot-Ginger Vinaigrette or opt for a healthy, store-bought Asian-style dressing. When buying salad dressing, choose one made with healthy fats, such as olive oil or canola oil. Cook a chicken breast for tomorrow's lunch or substitute precooked chicken or sliced chicken or turkey breast from the grocery store. When choosing deli items, go for low-sodium, preservative-free options.",

                ]
            },
            {
                name: "Day 4:",
                image: require('../assets/nutrition/image/1800.jpg'),
                procedure: [
                            "Breakfast (405 calories)",
                            "•	1/2 cup Maple-Nut Granola",
                            "•	1 cup non-fat plain Greek yogurt",
                            "•	1/4 cup blueberries",
                            "Morning Snack (305 calories)",
                            "•	1 medium apple",
                            "•	2 Tbsp. peanut butter",
                            "Lunch (417 calories)",
                            "• 2 cups mixed greens",
                            "• 4 oz. cooked chicken breast",
                            "• 1/2 medium red bell pepper, sliced",
                            "• 1/4 cup grated carrots",
                            "• 1 clementine, peeled and sectioned",
                            "• 2 Tbsp. Carrot-Ginger Vinaigrette",
                            "Combine ingredients and top the salad with the vinaigrette.",
                            "Afternoon Snack (172 calories)",
                            "•	8 dried apricots",
                            "•	8 walnut halves",
                            "Dinner (508 calories)",
                            "•	2 1/4 cups Warm Lentil Salad with Sausage & Apple",
                            "•	1/2 cup Quick Pickled Beets",
                            "•	1 diagonal slice baguette (1/4 inch thick), preferably whole-wheat",
                            "•	Top baguette with 1 tsp. butter",
                            "Meal Prep Tip: Make Avocado-Yogurt Dip for tomorrow. You can substitute store-bought hummus for the dip, if desired.",

                ]
            },
            {
                name: "Day 5:",
                image: require('../assets/nutrition/image/1800.jpg'),
                procedure: [
                            "Breakfast (369 calories)",
                            "•	1 cup all-bran cereal",
                            "•	3/4 cup skim milk",
                            "•	1/2 cup blueberries",
                            "•	2 Tbsp. unsalted dry-roasted almonds",
                            "Morning Snack (117 calories)",
                            "•	1 cup sliced cucumber",
                            "•	4 Tbsp. Avocado",
                            "Lunch (449 calories)",
                            "• 2 Tomato-Cheddar Cheese Toasts",
                            "• 2 cups mixed greens",
                            "• 1/4 cup grated carrot",
                            "• 1/2 cup cucumber, sliced",
                            "• 1 hard-boiled egg",
                            "• 2 Tbsp. unsalted dry-roasted almonds",
                            "• 1 1/2 tsp. each olive oil & balsamic vinegar",
                            "Top greens with carrot, cucumber, hard-boiled egg and almonds. Toss with balsamic vinaigrette.",
                            "Afternoon Snack (210 calories)",
                            "•	1 medium banana",
                            "•	8 walnut halves",
                            "Dinner (535 calories)",
                            "•	1 1/2 cups Quick Chicken Tikka Masala",
                            "•	1 cup brown rice",
                            "Evening Snack (133 calories)",
                            "• 2 Medjool dates",

                ]
            },
            {
                name: "Day 6:",
                image: require('../assets/nutrition/image/1800.jpg'),
                procedure: [
                            "Breakfast (369 calories)",
                            "•	1 cup all-bran cereal",
                            "•	3/4 cup skim milk",
                            "•	1/2 cup blueberries",
                            "•	2 Tbsp. unsalted dry-roasted almonds",
                            "Morning Snack(176 calories)",
                            "•	4 Tbsp. Avocado-Yogurt Dip",
                            "•	3 medium carrots",
                            "Lunch (440 calories)",
                            "Leftover Chicken Tikka Masala",
                            "• 1 1/2 cups Quick Chicken Tikka Masala",
                            "• 2 cups spinach",
                            "• 1/2 cup brown rice",
                            "Reheat the chicken on top of spinach in the microwave.",
                            "Afternoon Snack (210 calories)",
                            "•	1 medium banana",
                            "•	8 walnut halves",
                            "Dinner (604 calories)",
                            "•	2 cups Korean Beef Stir-Fry",
                            "•	1 cup cooked buckwheat soba noodles (about 2 ounces dry noodles)",
                            "Meal Prep Tip: Cook a chicken breast for tomorrow's lunch or substitute precooked chicken or sliced chicken or turkey breast from the grocery store. When choosing deli items, go for low-sodium, preservative-free options.",

                ]
            },
            {
                name: "Day 7:",
                image: require('../assets/nutrition/image/1800.jpg'),
                procedure: [
                            "Breakfast (362 calories)",
                            "•	1 cup all-bran cereal",
                            "•	3/4 cup skim milk",
                            "•	1/2 cup blueberries",
                            "•	2 Tbsp. chopped walnuts",
                            "Morning Snack (291 calories)",
                            "•	4 Tbsp. Avocado-Yogurt Dip",
                            "•	3 medium carrots",
                            "Lunch (434 calories)",
                            "• 2 cups mixed greens",
                            "• 4 oz. cooked chicken breast",
                            "• 1/2 medium red bell pepper, sliced",
                            "• 1/4 cup grated carrots",
                            "• 1 Tbsp. unsalted dry-roasted almonds",
                            "• 2 Tbsp. Carrot-Ginger Vinaigrette",
                            "• 1 clementine, peeled and sectioned",
                            "Combine ingredients and top the salad with the vinaigrette.",
                            "Afternoon Snack (142 calories)",
                            "• 1 hard-boiled egg",
                            "• 2 diagonal slices baguette (1/4 inch thick), preferably whole-wheat",
                            "• 1 tsp. hot sauce (if desired) Toast baguette slices and top with sliced egg and hot sauce.",
                            "Dinner (494 calories)",
                            "• 1 serving Wild Mushroom Pizza with Arugula & Pecorino",
                            "Evening Snack (76 calories)",
                            "• 1 1/2 Tbsp. chocolate chips, preferably dark chocolate",

                ]
            },
        ]
    },
    {
        type: "2,000 Calories",
        image: require('../assets/nutrition/image/2000.jpg'),
        data = [
            {
                name: "Day 1:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                            "Breakfast (479 calories)",
                            "•	1 serving Avocado-Egg Toast",
                            "•	1 medium banana",
                            "•	2 Tbsp. dry roasted, unsalted almonds",
                            "Morning Snack (196 calories)",
                            "•	1 cup plain non-fat Greek yogurt",
                            "•	1/2 cup blueberries",
                            "•	1 tsp. honey",
                            "Lunch (486 calories)",
                            "•	2 cups Ravioli & Vegetable Soup",
                            "•	2 Tomato-Cheddar Cheese Toasts",
                            "•	1 cup mixed greens",
                            "•	1 Tbsp. Carrot-Ginger Vinaigrette",
                            "Afternoon Snack (206 calories)",
                            "•	1/4 cup hummus",
                            "•	1 cup sliced cucumber",
                            "•	8 seeded crackers",
                            "Dinner (617 calories)",
                            "• 1 serving Smoky Maple-Mustard Salmon",
                            "• 1 cup Easy Brown Rice",
                            "• 1 1/2 Tbsp. chopped walnuts",
                            "• 1 cup green beans",
                            "• 1/4 tsp. salt and pepper, divided between the brown rice and green beans",
                            "• 2 tsp. olive oil, divided between the brown rice and green beans",
                            "Toss green beans in olive oil, salt and pepper and roast alongside the salmon. Mix the remaining oil in with the rice, season with salt and pepper, and top with chopped walnuts for an easy brown rice pilaf.",

                ]
            },
            {
                name: "Day 2:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (479 calories)",
                           "•	1 serving Avocado-Egg Toast",
                           "•	1 medium banana",
                           "•	2 Tbsp. dry roasted, unsalted almonds",
                           "Morning Snack(155 calories)",
                           "•	6 dried apricots",
                           "•	8 walnut halves",
                           "Lunch (502 calories)",
                           "Leftover soup",
                           "• 2 cups Ravioli & Vegetable Soup",
                           "• 1 3-inch thick slice baguette",
                           "• 1 medium orange",
                           "Afternoon Snack (206 calories)",
                           "•	1/4 cup hummus",
                           "•	1 cup sliced cucumber",
                           "•	8 seeded crackers",
                           "Dinner (665 calories)",
                           "•	1 1/2 cups Delicata Squash & Tofu Curry",
                           "•	1 cup Easy Brown Rice",
                           "•	2 cups mixed greens",
                           "•	2 Tbsp. Carrot-Ginger Vinaigrette",

                ]
            },
            {
                name: "Day 3:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (479 calories)",
                           "•	1/2 cup Maple-Nut Granola",
                           "•	1 cup plain non-fat Greek yogurt",
                           "•	1 cup blueberries",
                           "Morning Snack (165 calories)",
                           "•	1 medium orange",
                           "•	12 Tbsp. dry roasted, unsalted almonds",
                           "Lunch (513 calories)",
                           "•	1 serving Apple & Cheddar Pita Pockets",
                           "•	Remaining 1/2 apple, sliced",
                           "•	2 cups mixed greens dressed with 2 tsp. each olive oil & balsamic vinegar",
                           "Afternoon Snack (210 calories)",
                           "•	1 medium banana",
                           "•	1 Tbsp. peanut butter",
                           "Dinner (550 calories)",
                           "• 1 serving (1 pepper) Moroccan-Style Stuffed Peppers",
                           "• 3 cups spinach",
                           "Sauté spinach in 1 Tbsp. of olive oil and a pinch of both salt and pepper (1/16 tsp. each)",
                           "Evening Snack (101 calories)",
                           "• 2 Tbsp. chocolate chips, preferably dark chocolate",

                ]
            },
            {
                name: "Day 4:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (479 calories)",
                           "•	1/2 cup Maple-Nut Granola",
                           "•	1 cup plain non-fat Greek yogurt",
                           "•	1 cup blueberries",
                           "Morning Snack (165 calories)",
                           "•	2 hard-boiled eggs",
                           "•	2 tsp. hot sauce, if desired",
                           "Lunch (510 calories)",
                           "• 2 cups mixed greens",
                           "• 4 oz. cooked chicken breast",
                           "• 1/2 medium red bell pepper, sliced",
                           "• 1/4 cup grated carrots",
                           "• 1 Tbsp. slivered almonds",
                           "• 2 Tbsp. Carrot-Ginger Vinaigrette",
                           "Combine ingredients & top salad with vinaigrette.",
                           "• 1 medium orange",
                           "Afternoon Snack (199 calories)",
                           "•	1 medium apple",
                           "•	8 walnut halves",
                           "Dinner(624 calories)",
                           "•	1 serving Warm Lentil Salad with Sausage & Apple",
                           "•	1 serving Quick Pickled Beets",
                           "•	1 3-inch thick slice baguette",

                ]
            },
            {
                name: "Day 5:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (447 calories)",
                           "•	1 cup all-bran cereal",
                           "•	1 cup 2% milk",
                           "•	1 1/2 cup blueberries",
                           "Morning Snack (259 calories)",
                           "•	10 seeded crackers",
                           "•	2 medium carrots",
                           "•	1/4 cup Avocado-Yogurt Dip",
                           "Lunch (464 calories)",
                           "• 2 Tomato-Cheddar Cheese Toast",
                           "• 2 cups mixed greens",
                           "• 3 Tbsp. grated carrot",
                           "• 1/2 cup cucumber, sliced",
                           "• 1 hard-boiled egg",
                           "• 1 Tbsp. unsalted dry-roasted almonds",
                           "Top greens with grated carrot, cucumber, hard-boiled egg, almonds and 1 Tbsp. each olive oil & balsamic vinegar.",
                           "Afternoon Snack (206 calories)",
                           "• 1 cup plain non-fat Greek yogurt",
                           "• 1 Tbsp. chopped walnuts",
                           "• 3 dried apricots, chopped",
                           "Top yogurt with walnuts and apricots.",
                           "•	 1 serving Quick Chicken Tikka Masala",
                           "1 cup Easy Brown Rice",
                           "1 serving Simple Sautéed Spinach",

                ]
            },
            {
                name: "Day 6:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (447 calories)",
                           "•	1 cup all-bran cereal",
                           "•	1 cup all-bran cereal",
                           "•	1 1/2 cup blueberries",
                           "•	Morning Snack(224 calories)",
                           "•	10 seeded crackers",
                           "•	1 cup sliced cucumbers",
                           "•	1/4 cup Avocado-Yogurt Dip",
                           "Lunch (500 calories)",
                           "Leftover Chicken Tikka Masala",
                           "• 1 1/2 cups Quick Chicken Tikka Masala",
                           "• 1/2 cup Easy Brown Rice",
                           "• 1 cup spinach",
                           "Reheat the chicken on top of the spinach in the microwave.",
                           "• 1 medium orange",
                           "Afternoon Snack (200 calories)",
                           "•	1/2 medium apple, sliced",
                           "•	1 Tbsp. peanut butter",
                           "Dinner (604 calories)",
                           "•	2 cups Korean Beef Stir-Fry",
                           "•	2 cups cooked buckwheat soba noodles (about 4 ounce dry noodles)",

                ]
            },
            {
                name: "Day 7:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (447 calories)",
                           "•	1 cup all-bran cereal",
                           "•	1 cup 2% milk",
                           "•	1 1/2 cup blueberries",
                           "•	Morning Snack(224 calories)",
                           "•	10 seeded crackers",
                           "•	1 cup sliced cucumbers",
                           "•	1/4 cup Avocado-Yogurt Dip",
                           "Lunch (448 calories)",
                           "• 2 cups mixed greens",
                           "• 4 oz. cooked chicken breast",
                           "• 1/2 medium red bell pepper, sliced",
                           "• 1/4 cup grated carrots",
                           "• 1 Tbsp. slivered almonds",
                           "• 2 Tbsp. Carrot-Ginger Vinaigrette",
                           "Combine ingredients and top salad with vinaigrette.",
                           "• 1 medium orange",
                           "Afternoon Snack (78 calories)",
                           "• 6 walnut halves",
                           "Dinner (653 calories)",
                           "•	1 serving (1/4 pizza)Wild Mushroom Pizza with Arugula & Pecorino",
                           "•	2 cups mixed greens dressed with 1 Tbsp. each olive oil & balsamic vinegar",
                           "Evening Snack (151 calories)",
                           "• 3 Tbsp. chocolate chips, preferably dark chocolate",

                ]
            },
        ]
    },
    {
        type: "2,400 Calories",
        image: require('../assets/nutrition/image/2400.jpg'),
        data = [
            {
                name: "Day 1:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (489 calories)",
                           "•	Avocado-Egg Toast",
                           "•	1 slice whole-grain bread",
                           "•	1/2 medium avocado",
                           "•	2 large eggs, cooked in 1/4 tsp. olive oil or coat pan with a thin layer of cooking spray (1-second spray)",
                           "•	Season egg with a pinch of salt and pepper.",
                           "•	1 medium banana",
                           "Morning Snack (305 calories)",
                           "•	1 medium apple",
                           "•	2 Tbsp. peanut butter",
                           "Lunch (508 calories)",
                           "•	2 cups Ravioli & Vegetable Soup",
                           "•	2 diagonal slices baguette (1/4 inch thick), preferably whole-wheat",
                           "•	3 Tbsp. shredded Cheddar cheese",
                           "•	Top baguette slices with 1 1/2 Tbsp. cheese each and a pinch of pepper. Toast until cheese is melted.",
                           "•	1 medium pear",
                           "Afternoon Snack(245 calories)",
                           "•	5 Tbsp. hummus",
                           "•	1 cup sliced cucumber",
                           "•	4 medium carrots",
                           "Dinner (641 calories)",
                           "•	Salmon & Vegetables",
                           "•	5 oz. baked salmon",
                           "•	1 cup roasted Brussels sprouts",
                           "•	1 cup brown rice",
                           "•	1/8 tsp. salt",
                           "•	1/8 tsp. pepper",
                           "•	1 1/2 Tbsp. walnuts",
                           "•	Vinaigrette",
                           "•	Combine 1 1/2 tsp. each olive oil, lemon juice and maple syrup; season with 1/8 tsp. salt.",
                           "Toss Brussels sprouts with 1/2 tsp. olive oil and bake at 425°F until lightly browned, 15 to 20 minutes. Coat salmon with 1/4 tsp. olive oil or a thin layer of cooking spray (1-second spray) and season with 1/8 tsp. each salt and pepper. Bake at 425°F until opaque in the middle, 4 to 6 minutes. Serve Brussels sprouts, salmon and brown rice drizzled with the vinaigrette and topped with walnuts.",

                ]
            },
            {
                name: "Day 2:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (485 calories)",
                           "•	Avocado-Egg Toast",
                           "•	1 slice whole-grain bread",
                           "•	1/2 medium avocado",
                           "•	2 large eggs, cooked in 1/4 tsp. olive oil or coat pan with a thin layer of cooking spray (1-second spray)",
                           "•	Season egg with a pinch of salt and pepper.",
                           "•	1 medium pear",
                           "Morning Snack (323 calories)",
                           "•	7 dried apricots",
                           "•	7 walnut halves",
                           "•	1 1/2 oz. Cheddar cheese",
                           "Lunch (508 calories)",
                           "Leftover soup",
                           "•	2 cups Ravioli & Vegetable Soup",
                           "•	2 diagonal slices baguette (1/4 inch thick), preferably whole-wheat",
                           "•	3 Tbsp. shredded Cheddar cheese",
                           "•	Top each baguette slice with 1 1/2 Tbsp. cheese and a pinch of pepper. Toast until cheese is melted.",
                           "•	1 medium pear",
                           "Afternoon Snack(230 calories)",
                           "•	5 Tbsp. hummus",
                           "•	4 medium carrots",
                           "Dinner(533 calories)",
                           "•	1 1/2 cups Delicata Squash & Tofu Curry",
                           "•	Serve curry over 1 cup brown rice",
                           "Evening Snack (133 calories)",
                           "• 2 Medjool dates",
                           "Meal Prep Tip: Make Maple-Nut Granola for tomorrow. You can also buy granola, to make things easier. Aim for a granola that has around 130 calories (or less) and less than 6 grams of sugar per 1/4 cup.",

                ]
            },
            {
                name: "Day 3:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (488 calories)",
                           "•	1/2 cup Maple-Nut Granola",
                           "•	1 cup non-fat plain Greek yogurt",
                           "•	1/2 cup blueberries",
                           "•	1 medium orange",
                           "Morning Snack(245 calories)",
                           "•	5 Tbsp. hummus",
                           "•	4 medium carrots",
                           "•	1 cup sliced cucumbers",
                           "Lunch (518 calories)",
                           "•	Apple & Cheddar Pita Pocket",
                           "•	1 whole-wheat pita round (6-1/2-inch)",
                           "•	1 Tbsp. mustard",
                           "•	1/2 medium apple, sliced",
                           "•	2 oz. Cheddar cheese",
                           "•	1 cup mixed greens",
                           "•	Cut pita in half and spread mustard inside. Fill with apple slices and cheese. Toast until the cheese begins to melt. Add greens and serve.",
                           "•	4 walnut halves",
                           "Afternoon Snack (331 calories)",
                           "•	1/2 medium apple, sliced",
                           "•	1 1/2 Tbsp. peanut butter",
                           "•	1/4 cup Maple-Nut Granola",
                           "•	Dip apple slices into peanut butter and granola.",
                           "Dinner (507 calories)",
                           "•	1Moroccan-Style Stuffed Pepper",
                           "•	2 cups spinach",
                           "•	Sauté spinach in 1 tsp. olive oil with a pinch of salt and pepper.",
                           "•	1 cup sliced carrots, steamed",
                           "Evening Snack (101 calories)",
                           "• 2 Tbsp. chocolate chips, preferably dark chocolate",
                           "Meal Prep Tip: Hard-boil 2 eggs-save one for Day 7. Make Carrot-Ginger Vinaigrette or opt for a healthy, store-bought Asian-style dressing. When buying salad dressing, choose one made with healthy fats, such as olive oil or canola oil. Cook a chicken breast for tomorrow's lunch or substitute precooked chicken or sliced chicken or turkey breast from the grocery store. When choosing deli items, go for low-sodium, preservative-free options.",

                ]
            },
            {
                name: "Day 4:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (488 calories)",
                           "•	1/2 cup Maple-Nut Granola",
                           "•	1 cup non-fat plain Greek yogurt",
                           "•	1/2 cup blueberries",
                           "•	1 medium orange",
                           "Morning Snack (305 calories)",
                           "•	1 medium apple",
                           "•	2 Tbsp. peanut butter",
                           "Lunch (512 calories)",
                           "•	2 cups mixed greens",
                           "•	4 oz. cooked chicken breast",
                           "•	1/2 medium red bell pepper, sliced",
                           "•	1/4 cup grated carrots",
                           "•	2 Tbsp. unsalted dry-roasted almonds",
                           "•	2 Tbsp. Carrot-Ginger Vinaigrette",
                           "•	Combine ingredients and top the salad with the vinaigrette.",
                           "•	1 medium orange",
                           "Afternoon Snack (235 calories)",
                           "•	1 medium banana",
                           "•	10 walnut halves",
                           "Dinner (652 calories)",
                           "•	2 1/4 cups Warm Lentil Salad with Sausage & Apple",
                           "•	2/3 cup Quick Beet Salad",
                           "•	2 diagonal slices baguette (1/4 inch thick), preferably whole-wheat",
                           "•	Top baguette with 1 tsp. butter",
                           "Meal Prep Tip: Make Avocado-Yogurt Dip for tomorrow. You can substitute store-bought hummus for the dip, if desired.",

                ]
            },
            {
                name: "Day 5:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (472 calories)",
                           "•	1 1/4 cups all-bran cereal",
                           "•	3/4 cup skim milk",
                           "•	1 medium banana",
                           "•	2 Tbsp. unsalted dry-roasted almonds",
                           "Morning Snack (192 calories)",
                           "•	4 Tbsp. Avocado-Yogurt Dip",
                           "•	1 cup sliced cucumber",
                           "•	3 medium carrots",
                           "Lunch (519 calories)",
                           "•	2 Tomato-Cheddar Cheese Toasts",
                           "•	2 cups mixed greens",
                           "•	1/4 cup grated carrot",
                           "•	1/2 cup cucumber, sliced",
                           "•	1 hard-boiled egg",
                           "•	2 Tbsp. unsalted dry-roasted almonds",
                           "•	1 Tbsp. each olive oil & balsamic vinegar",
                           "•	Top greens with carrot, cucumber, hard-boiled egg and almonds. Toss with balsamic vinaigrette.",
                           "Afternoon Snack (346 calories)",
                           "•	1/2 cup blueberries",
                           "•	10 walnut halves",
                           "•	1 1/2 oz. Cheddar cheese",
                           "Dinner (668 calories)",
                           "•	1 1/2 cups Quick Chicken Tikka Masala",
                           "•	1 cup brown rice",
                           "•	2 medjool dates to enjoy after dinner",

                ]
            },
            {
                name: "Day 6:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (469 calories)",
                           "•	1 1/4 cups all-bran cereal",
                           "•	3/4 cup skim milk",
                           "•	1 medium pear",
                           "•	2 Tbsp. unsalted dry-roasted almonds",
                           "Morning Snack (291 calories)",
                           "•	4 Tbsp. Avocado-Yogurt Dip",
                           "•	3 medium carrots",
                           "•	1 oz. Cheddar cheese",
                           "Lunch (494 calories)",
                           "•	Leftover Chicken Tikka Masala",
                           "•	1 1/2 cups Quick Chicken Tikka Masala",
                           "•	2 cups spinach",
                           "•	3/4 cup brown rice",
                           "•	Reheat the chicken on top of spinach in the microwave.",
                           "Afternoon Snack (249 calories)",
                           "•	1 medium banana",
                           "•	11 walnut halves",
                           "Dinner (604 calories)",
                           "•	1 cups Korean Beef Stir-Fry",
                           "•	1 cup cooked buckwheat soba noodles (about 2 ounces dry noodles)",
                           "Evening Snack (86 calories)",
                           "• 1 serving Cinnamon Oranges",
                           "Meal Prep Tip: Cook a chicken breast for tomorrow's lunch or substitute precooked chicken or sliced chicken or turkey breast from the grocery store. When choosing deli items, go for low-sodium, preservative-free options.",

                ]
            },
            {
                name: "Day 7:",
                image: require('../assets/nutrition/image/2000.jpg'),
                procedure: [
                           "Breakfast (466 calories)",
                           "•	1 1/4 cups all-bran cereal",
                           "•	3/4 cup skim milk",
                           "•	1 medium banana",
                           "•	2 Tbsp. chopped walnuts",
                           "Morning Snack (349 calories)",
                           "•	4 Tbsp. Avocado-Yogurt Dip",
                           "•	3 medium carrots",
                           "•	1 1/2 oz. Cheddar cheese",
                           "Lunch (512 calories)",
                           "•	2 cups mixed greens",
                           "•	4 oz. cooked chicken breast",
                           "•	1/2 medium red bell pepper, sliced",
                           "•	1/4 cup grated carrots",
                           "•	2 Tbsp. unsalted dry-roasted almonds",
                           "•	2 Tbsp. Carrot-Ginger Vinaigrette",
                           "•	Combine ingredients and top the salad with the vinaigrette.",
                           "•	1 medium orange",
                           "Afternoon Snack (209 calories)",
                           "•	1 hard-boiled egg",
                           "•	2 diagonal slices baguette (1/4 inch thick), preferably whole-wheat",
                           "•	1 tsp. hot sauce (if desired)",
                           "•	Toast baguette slices and top with sliced egg and hot sauce.",
                           "•	4 dried apricots",
                           "•	 1 serving Wild Mushroom Pizza with Arugula & Pecorino",
                           "•	 2 Tbsp. chocolate chips, preferably dark chocolate, and 1 serving Cinnamon Oranges to enjoy after dinner",
                           
                ]
            },
        ]
    },
    {
        type: "Ketogenic",
        image: require('../assets/nutrition/image/Ketogenic.jpg'),
        data = [
            {
                name: "Day 1:",
                image: require('../assets/nutrition/image/Ketogenic.jpg'),
                procedure: [
                           "BREAKFAST",
                           "3 Egg Omelet with Spinach, Cheese, and Sausage:",
                           "Make a healthy omelet with some cheddar, crumbled breakfast sausage, and shredded spinach and you’re already looking at over 30g of protein.",
                           "LUNCH",
                           "BLT Salad:",
                           "Take 2 – 3 cups of lettuce, crumble in some bacon and dice a medium tomato.",
                           "Mix that with two or three tablespoons of mayo, and toss after adding some splashes of hot sauce.",
                           "DINNER",
                           "Baked Salmon with Asparagus:",
                           "A simple sauce of butter, lemon juice, chopped garlic, and some salt and pepper will go a long way to enhancing the natural flavor of the salmon.",
                           "Drizzle the sauce over 4-6 oz portions of fish, bake at 450F for 5 minutes per 1/2″ thickness of fish.",
                           "In another bowl, toss the asparagus with olive oil, salt, and pepper, spread it out evenly on a cookie sheet, and roast in the oven at 450 for 20 minutes.",
                           
                ]
            },
            {
                name: "Day 2:",
                image: require('../assets/nutrition/image/Ketogenic.jpg'),
                procedure: [
                          "BREAKFAST",
                          "Bacon and Eggs:",
                          "2 or 3 fried eggs and some bacon might not sound like much, but it’s full of protein that will keep you full and energized all morning.",
                          "Take the opportunity on the weekend to lay your bacon strips on a single cookie sheet and bake in the oven for 20 minutes at 400 degrees.",
                          "LUNCH",
                          "Spinach Salad:",
                          "A bed of spinach with some red onion, bacon, a little tomato, and a hot sauce vinaigrette.",
                          "Add in some protein – perhaps that leftover salmon from day 1.",
                          "Hot sauce vinaigrette – 1/2 cup olive oil, 1/4 cup vinegar, hot sauce to taste – mix together and apply to salad.",
                          "DINNER",
                          "Cheese-Stuffed Bun less Burgers:",
                          "Cook a couple of fresh beef patties, and then top one in cheese and stack the other on top.",
                          "Stick them on a plate and cover in veggies and low carb sauces.",
                           
                ]
            },
            {
                name: "Day 3:",
                image: require('../assets/nutrition/image/Ketogenic.jpg'),
                procedure: [
                           "BREAKFAST",
                           "Eggies:",
                           "Beat 8 eggs in a bowl, add in cheese and vegetables, and pour into muffin tins that have been lined with a strip of bacon.",
                           "Cook at 350 for 30 minutes, or until a toothpick stuck in the middle comes out clean. Store in baggies for breakfast for up to 5 days.",
                           "LUNCH",
                           "Cottage Cheese, Walnuts, and Hot Sauce.",
                           "DINNER",
                           "Meatloaf:",
                           "Using chopped mushrooms and onions as a binder instead of bread crumbs adds flavor and nutrients, and keeps carbs down.",
                           
                ]
            },
            {
                name: "Day 4:",
                image: require('../assets/nutrition/image/Ketogenic.jpg'),
                procedure: [
                           "BREAKFAST",
                           "Eggies:",
                           "Beat 8 eggs in a bowl, add in cheese and vegetables, and pour into muffin tins that have been lined with a strip of bacon.",
                           "Cook at 350 for 30 minutes, or until a toothpick stuck in the middle comes out clean. Store in baggies for breakfast for up to 5 days.",
                           "LUNCH",
                           "Tuna Salad Lettuce Wraps:",
                           "Making a tuna salad with low carb ingredients is easy and delicious, doubly so when you chop up some fresh avocado into said salad.",
                           "Using sheathes of endive or romaine lettuce to transport and eat the salad is even better.",
                           "DINNER",
                           "Slaw Hash:",
                           "Shred a head of cabbage, and cook with onions, ground beef, soy sauce, red pepper flakes, butter, and garlic.",
                           
                ]
            },
            {
                name: "Day 5:",
                image: require('../assets/nutrition/image/Ketogenic.jpg'),
                procedure: [
                           "BREAKFAST",
                           "Eggies:",
                           "Beat 8 eggs in a bowl, add in cheese and vegetables, and pour into muffin tins that have been lined with a strip of bacon.",
                           "Cook at 350 for 30 minutes, or until a toothpick stuck in the middle comes out clean. Store in baggies for breakfast for up to 5 days.",
                           "LUNCH",
                           "Spam Fries and Cole Slaw:",
                           "If you saved some cabbage (uncooked) from last night’s dinner, make a simple slaw using low carb ingredients, and chop up some spam into fry-like sections, and fry them up in a frying pan, or bake them for 20 minutes at 350. Serve with ranch or low carb ketchup.",
                           "DINNER",
                           "Tacos:",
                           "Use your favorite taco recipe, cook up some beef, and use romaine for shells.",
                           "Add in some full fat sour cream and cheese, and you'll never miss the tortillas.",
                           
                ]
            },
            {
                name: "Day 6:",
                image: require('../assets/nutrition/image/Ketogenic.jpg'),
                procedure: [
                    "BREAKFAST",
                    "Eggies:",
                    "Beat 8 eggs in a bowl, add in cheese and vegetables, and pour into muffin tins that have been lined with a strip of bacon.",
                    "Cook at 350 for 30 minutes, or until a toothpick stuck in the middle comes out clean. Store in baggies for breakfast for up to 5 days.",
                    "LUNCH",
                    "Taco Salad:",
                    "Take your leftover tacos and make a huge taco salad.",
                    "Top with salsa and sour cream, and some shredded cheese.",
                    "Fat, protein, and veggies will fill you up all day.",
                    "DINNER",
                    "Pork Roast and Roasted Veggies:",
                    "A nice pork roast, rubbed down with cumin, salt, and garlic, will give you leftovers for days, tastes amazing, and is pretty cheap.",
                    "Pair that with some Brussels sprouts, broccoli, or cauliflower that has been roasted in the oven until brown.",
                           
                ]
            },
            {
                name: "Day 7:",
                image: require('../assets/nutrition/image/Ketogenic.jpg'),
                procedure: [
                    "BREAKFAST",
                    "Avocado-Baked Eggs:",
                    "Cut an avocado in 2, crack an egg in the seed hole, and bake until the egg is set.",
                    "LUNCH",
                    "Chicken and Hummus Lettuce Wraps:",
                    "Deli sliced chicken, spread with savory hummus and wrapped up in butter lettuce, is a quick, healthy lunch that provides a protein punch and without a ton of calories.",
                    "DINNER",
                    "Philly Cheesesteak Casserole:",
                    "Using your leftover pork roast, mix with sliced onions and peppers, cream cheese, and shredded cheddar, and bake in the oven for 30 minutes at 350.",
                           
                ]
            },
        ]
    },
]